src/accounts/urls.py
from django.urls import path

from accounts.views import (
    UserRegisterView,
    UserLoginView,
    UserLogoutView,
    activate_account_view,
)

app_name = "accounts"

urlpatterns = [
    path("sign-up/", UserRegisterView.as_view(), name="sign-up"),
    path("sign-in/", UserLoginView.as_view(), name="sign-in"),
    path("sign-out/", UserLogoutView.as_view(), name="sign-out"),
    path("activate/<uidb64>/<token>/", activate_account_view, name="activate"),
]

src/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("exchange/", include("exchange.urls", namespace="exchange")),
    path("user/", include("accounts.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    AMLRulesView,
    RaffleView,
    CashbackInfoView,
    DepositView,
    tonconnect_manifest,
    WalletTonService,
)

app_name: str = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("aml/", AMLRulesView.as_view(), name="aml"),
    path("raffle/", RaffleView.as_view(), name="raffle"),
    path("cashback-info/", CashbackInfoView.as_view(), name="cashback"),
    path("deposit/", DepositView.as_view(), name="deposit"),
    path("tonconnect-manifest.json", tonconnect_manifest, name="tonconnect_manifest"),
    path("api/wallet-balance/", WalletTonService.as_view(), name="wallet_balance"),
]

src/templates/partials/base.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="format-detection" content="telephone=no" />
    <meta name="format-detection" content="address=no" />
    <meta name="PalmComputingPlatform" content="true" />
    <meta name="apple-touch-fullscreen" content="yes" />
    <link rel="profile" href="https://gmpg.org/xfn/11">
    <title>{% block title %}{{ title }}{% endblock %}</title>

    <meta name='robots' content='max-image-preview:large' />
    <link rel='dns-prefetch' href='//fonts.googleapis.com' />
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel='stylesheet' id='oswald-sans-css' href='https://fonts.googleapis.com/css2?family=Oswald%3Awght%40500%3B600&#038;display=swap&#038;ver=2.7' type='text/css' media='all' />
    <link rel='stylesheet' id='montserrat-sans-css' href='https://fonts.googleapis.com/css2?family=Montserrat%3Aital%2Cwght%400%2C300%3B0%2C400%3B0%2C500%3B0%2C600%3B0%2C700%3B1%2C300%3B1%2C400%3B1%2C500%3B1%2C600%3B1%2C700&#038;display=swap&#038;ver=2.7' type='text/css' media='all' />
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/classic-themes.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/global-styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/flash-messages.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="{% static 'js/modal-ajax.js' %}"></script>
    <script src="{% static 'js/FlashMessage.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://unpkg.com/@tonconnect/ui@latest/dist/tonconnect-ui.min.js"></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery/script.min.js?ver=3.7.1' id='jquery-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-ui/script.min.js?ver=1.14.0' id='jquery-ui-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-forms/script.min.js?ver=3.51' id='jquery-forms-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-cook/script.min.js?ver=0.1' id='jquery-cookie-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-clipboard/script.min.js?ver=2.0.11' id='jquery-clipboard-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-window/script.min.js?ver=0.9' id='jquery-window-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-changeinput/script.min.js?ver=0.1' id='jquery-changeinput-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-select/script.min.js?ver=0.7' id='jquery select-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-table/script.min.js?ver=0.5' id='jquery-table-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-checkbox/script.min.js?ver=0.2' id='jquery-checkbox-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/site.js?ver=2.7' id='jquery-site-js-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/plugins/premiumbox/premium/js/jquery-timer/script.min.js?ver=0.3' id='jquery js timer-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/swiper/swiper-bundle.min.js?ver=1.0' id='swiper-bundle-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js?ver=1.0' id='mCustomScrollbar-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/jquery.countdown.js?ver=1.1' id='jquery-countdown-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/wow.min.js?ver=1.0' id='wow-js'></script>
    <script type='text/javascript' src='https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/js/scripts.js?ver=3.2' id='scripts-js-js'></script>
    <link rel="shortcut icon" href="https://crypto-chicken.co/wp-content/uploads/logo-chicken.png" type="image/png" />
    <link rel="icon" href="https://crypto-chicken.co/wp-content/uploads/logo-chicken.png" type="image/png" />
</head>

    {% block content %}{% endblock %}

src/templates/partials/footer.html
{% load static %}


<footer class="footer">
    <div class="container">
        <div class="footer__inner">
            <div class="footer__left">
                <div class="footer__tt title">График работы: 24/7</div>
                <div class="footer__cm">
                    <div class="footer__contacts">
                        <div class="footer__contacts-label">График работы поддержки:</div>
                        <div class="footer__contacts-val">
                            пн-cб с 9:00 до 19:00 UTC+3 </div>
                        <div class="footer__buttons footer__social social">
                            <a href="https://t.me/CryptoChickenOfficial" class="social__item" target="_blank"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/social/tg.svg" alt=""></a> <a href="https://www.instagram.com/cryptochickennews/" class="social__item" target="_blank"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/social/insta.svg" alt=""></a> <a href="javascript:void(0)" class="social__item btn--chat"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/social/message.svg" alt=""></a>
                            <a href="/cdn-cgi/l/email-protection#046d6a626b4467767d74706b29676c6d676f616a2a676b" class="social__item" target="_blank"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/social/mail.svg" alt=""></a> </div>
                    </div>
                    <div class="footer__menu">
                        <ul id="menu-nizhnee-menyu-footer-menu" class="hmenu">
                            <li id="menu-item-1087" class="menu-item menu-item-type-post_type menu-item-object-page  first_menu_li menu-item-1087"><a href="{% url 'core:aml' %}"><span>AML правила</span></a></li>
                            <li id="menu-item-1201" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1201"><a href="{% url 'core:raffle' %}"><span>Розыгрыш</span></a></li>
                            <li id="menu-item-1088" class="menu-item menu-item-type-post_type menu-item-object-page  last_menu_li menu-item-1088"><a href="{% url 'core:cashback' %}"><span>Kэшбэк</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="footer__partners">
                <div class="footer__partners-item">
                    <a href="https://www.bestchange.ru/cryptochicken-exchanger.html" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/best-change.png" alt="Bestchange.ru">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://exchangesumo.com/exchanger/1123/Crypto-chicken/" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/exchange-1.png" alt="Exchangesumo.com">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://e-mon.cc/" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/emon.png" alt="e-mon">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://kurs.expert/ru/obmennik/crypto-chicken-co/feedbacks.html" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/kurs.png" alt="Kurs.expert">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://crypto-control.org/" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/crypto-control.png" alt="Cryptocontrol">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://bits.media/exchanger/crypto-chicken-co" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/bits.png" alt="">
                    </a> </div>
                <div class="footer__partners-item">
                    <a href="https://kursoff.biz/ru/exchangers/cryptochicken" rel="nofollow noreferrer noopener" target="_blank"> <img src="https://crypto-chicken.co/wp-content/uploads/kursoff.png" alt="Kursoff">
                    </a> </div>
            </div>
        </div>

        <div class="footer__bottom">
            <p>Сервис обмена электронных валют.</p>
        </div>
    </div>
</footer>

src/templates/partials/header.html
{% load static %}

<style>
.wallet-btn-content {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 7px;
}

.wallet-balance-display {
    font-size: 16px;
    font-weight: 700;
    color: #fff;
    transition: font-size 0.2s;
}

.wallet-address-display {
    font-size: 15px;
    font-weight: 700;
    color: #fff;
    margin-left: 7px;
    margin-right: 0;
    letter-spacing: 0.5px;
}
</style>

<header class="header">
    <div class="container">
        <div class="header__inner">
            <div class="header__sname">
                <a href="https://crypto-chicken.co/" class="header__logo">
                    <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/logo.svg" alt="">
                </a>
                <div class="header__name"><a href="{% url 'core:index' %}">CryptoChicken</a></div>
            </div>
            <div class="header__right">
                <div class="header__top">
                    <div id="header-wallet-container">
                        <button id="header-connect-btn" class="btn btn--md btn--bd" type="button">
                            <i class="fas fa-wallet"></i>
                            <span>Connect Wallet</span>
                        </button>
                        <div id="wallet-button-container" style="position: relative; display: none;">
                            <button id="header-wallet-info" class="btn btn--md btn--bd" type="button">
                                <div class="wallet-btn-content">
                                    <span class="wallet-balance-display">Loading...</span>
                                    <span class="wallet-address-display">Connecting...</span>
                                </div>
                            </button>
                            <div id="wallet-dropdown" class="wallet-dropdown-modal" style="display: none;">
                                <div class="wallet-dropdown-header">
                                    <div class="wallet-dropdown-title">
                                        <img src="{% static 'img/tonconnect-icon.png' %}" alt="Wallet" class="wallet-icon-dropdown-img">
                                        <span class="dropdown-wallet-address" id="dropdown-wallet-address">Connecting...</span>
                                    </div>
                                    <div class="wallet-actions-icons">
                                        <button class="wallet-icon-btn" onclick="copyWalletAddress()" title="Copy Address">
                                            <i class="fas fa-copy"></i>
                                        </button>
                                        <button class="wallet-icon-btn" onclick="refreshWalletBalance()" title="Refresh Balance">
                                            <i class="fas fa-sync-alt"></i>
                                        </button>
                                        <button class="wallet-icon-btn disconnect-btn" onclick="disconnectWalletFromDropdown()" title="Disconnect">
                                            <i class="fas fa-sign-out-alt"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="wallet-dropdown-body">
                                    <div class="wallet-balance-section-dropdown">
                                        <div class="balance-label-dropdown">Баланс TON</div>
                                        <div class="balance-amount-dropdown" id="dropdown-wallet-balance">Loading...</div>
                                    </div>
                                </div>
                                <div class="wallet-dropdown-decoration"></div>
                            </div>
                        </div>
                    </div>
                    <div class="header__lang js-lang">
                        <div class="header__lang-current">
                            <span>RU</span>
                            <button class="header__lang-open js-lang-open"></button>
                        </div>
                        <div class="header__lang-drop js-lang-drop">
                            <ul>
                                <li class="current"><a href="">RU</a></li>
                                <li><a href="https://crypto-chicken.co/premium_site_action-set_site_lang.html?meth=get&yid=451a96c1cac6&ynd=0&lang=ru&return_url=https%3A%2F%2Fcrypto-chicken.co%2Fen%2F" rel="nofollow">EN</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div id="ton-connect-header" style="display: none;"></div>
                <div class="header__bottom">
                    <div class="header__nav">
                        <ul id="menu-verhnee-menyu" class="hmenu">
                            <li id="menu-item-1101" class="menu-item menu-item-type-post_type menu-item-object-page  first_menu_li menu-item-1101"><a href="{% url 'core:aml' %}"><span>AML правила</span></a></li>
                            <li id="menu-item-1200" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1200"><a href="{% url 'core:raffle' %}"><span>Розыгрыш</span></a></li>
                            <li id="menu-item-1189" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1189"><a href="{% url 'core:cashback' %}"><span>Kэшбэк</span></a></li>
                            <li id="menu-item-1279" class="menu-item menu-item-type-post_type menu-item-object-page  last_menu_li menu-item-1279"><a href="{% url 'core:deposit' %}"><span>Депозиты</span></a></li>
                        </ul>
                    </div>
                    {% if user.is_authenticated %}
                    <button class="btn btn--md btn--bd header__btnlog js-open-menu-acc">
                        <span>{{ user.username }}</span>
                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/drop.svg" alt="">
                    </button>
                    {% else %}
                    <div class="header__profile">
                        <div class="header__lg">
                            <button class="btn btn--md btn--bd btn--bdg" data-open-login="reg"><span>Регистрация</span></button>
                        </div>
                        <button class="btn btn--md btn--pdsm header__btnlog" data-open-login="login">
                            <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/in.svg" alt="">
                            <span>Войти</span>
                        </button>
                    </div>
                    <button class="header__login" data-open-login="login"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/in-color.svg" alt=""></button>
                    {% endif %}

                    <div class="accmenu js-menu-acc">
                        <ul>
                            <li><a href=""><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/profile-menu.svg" alt=""><span>Профиль</span></a></li>
                            <li><a href=""><img src="https://crypto-chicken.co/ваши-wp-content/themes/cryptochicken-new-design/images/icons/order-menu.svg" alt=""><span>заявки</span></a></li>
                            <li><a href=""><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/order-menu.svg" alt=""><span>Депозиты</span></a></li>
                            <li><a href=""><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/cashback-menu.svg" alt=""><span>Кешбэк</span></a></li>
                            <li><a href=""><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/check-menu.svg" alt=""><span>AML проверка кошелька</span></a></li>

                            <li>
                                <form action="{% url 'accounts:sign-out' %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="accmenu__btnlogout">
                                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/out-menu.svg" alt="">
                                        <span>Выход</span>
                                    </button>
                                </form>
                            </li>
                        </ul>
                    </div>

                    <button class="btn btn--md header__burger js-open-nav">
                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/burger.svg" class="hide-tablet-sm" alt="">
                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/closed.svg" class="icon-close hide-tablet-sm" alt="">
                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/menu_open.svg" class="show-tablet-sm" alt="">
                        <img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/menu_closed.svg" class="icon-close show-tablet-sm" alt="">
                    </button>
                </div>
            </div>
        </div>
        <div class="accmenu js-menu-acc">
        </div>

        {% include "accounts/sign-in.html" %}
        {% include "accounts/sign-up.html" %}
    </div>

    <div class="navfix js-navfix">
        <div class="container">
            <div class="navfix__nav">
                <ul id="menu-verhnee-menyu-1" class="hmenu">
                    <li class="menu-item menu-item-type-post_type menu-item-object-page  first_menu_li menu-item-1101"><a href="{% url 'core:aml' %}"><span>AML правила</span></a></li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1200"><a href="{% url 'core:raffle' %}"><span>Розыгрыш</span></a></li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1189"><a href="{% url 'core:cashback' %}"><span>Kэшbэк</span></a></li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page  last_menu_li menu-item-1279"><a href="{% url 'core:deposit' %}"><span>Депозиты</span></a></li>
                </ul>
            </div>

            <div class="navfix__contacts">
                <a href="/cdn-cgi/l/email-protection#3950575f56795a4b40494d56145a51505a525c57175a56" class="navfix__contacts-val"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/mail.svg" alt=""><span><span class="__cf_email__" data-cfemail="6900070f06290a1b10191d06440a01000a020c07470a06">[email&#160;protected]</span></span></a>
                <br>
                <a href="tg://resolve?domain=CryptoChicken_bot" class="navfix__contacts-val"><img src="https://crypto-chicken.co/wp-content/themes/cryptochicken-new-design/images/icons/tg.svg" alt=""><span>@CryptoChicken_bot</span></a> <br>
            </div>

            <div class="navfix__lang">
                <a href="https://crypto-chicken.co/premium_site_action-set_site_lang.html?meth=get&yid=451a96c1cac6&ynd=0&lang=ru&return_url=https%3A%2F%2Fcrypto-chicken.co%2F" class="navfix__lang-item active"><span>RU</span></a>
                <a href="https://crypto-chicken.co/premium_site_action-set_site_lang.html?meth=get&yid=451a96c1cac6&ynd=0&lang=ru&return_url=https%3A%2F%2Fcrypto-chicken.co%2Fen%2F" class="navfix__lang-item"><span>EN</span></a></div>
            <div class="navfix__buttons">
                <button class="btn btn--bd btn--md btn--chat"><span>Онлайн чат</span></button>
            </div>
        </div>
    </div>
    {% if messages %}
    <div class="flash-messages-container">
        {% for message in messages %}
        <div class="flash-message flash-{{ message.tags }}">
            <div class="flash-icon">
                {% if message.tags == 'success' %}
                <i class="fas fa-check-circle"></i>
                {% elif message.tags == 'error' %}
                <i class="fas fa-times-circle"></i>
                {% elif message.tags == 'warning' %}
                <i class="fas fa-exclamation-circle"></i>
                {% else %}
                <i class="fas fa-bell"></i>
                {% endif %}
            </div>
            <span class="flash-text">{{ message }}</span>
            <button class="flash-close" onclick="closeFlashMessage(this)">
                <i class="fas fa-times"></i>
            </button>
        </div>
        {% endfor %}
    </div>
    {% endif %}

</header>

<script src="{% static 'js/wallet-manager/ton-wallet.js' %}"></script>