src/accounts/urls.py
from django.urls import path

from accounts.views import (
    UserRegisterView,
    UserLoginView,
    UserLogoutView,
    activate_account_view,
)

app_name = "accounts"

urlpatterns = [
    path("sign-up/", UserRegisterView.as_view(), name="sign-up"),
    path("sign-in/", UserLoginView.as_view(), name="sign-in"),
    path("sign-out/", UserLogoutView.as_view(), name="sign-out"),
    path("activate/<uidb64>/<token>/", activate_account_view, name="activate"),
]

src/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls.conf import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("exchange/", include("exchange.urls", namespace="exchange")),
    path("user/", include("accounts.urls", namespace="account")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from core.views import (
    IndexView,
    AMLRulesView,
    RaffleView,
    CashbackInfoView,
    DepositView,
    tonconnect_manifest,
    WalletTonService,
)

app_name: str = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("aml/", AMLRulesView.as_view(), name="aml"),
    path("raffle/", RaffleView.as_view(), name="raffle"),
    path("cashback-info/", CashbackInfoView.as_view(), name="cashback"),
    path("deposit/", DepositView.as_view(), name="deposit"),
    path("tonconnect-manifest.json", tonconnect_manifest, name="tonconnect_manifest"),
    path("api/wallet-balance/", WalletTonService.as_view(), name="wallet_balance"),
]

src/accounts/models.py
from django.conf import settings
from django.utils import timezone

from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    email = models.EmailField(_("email address"), unique=True)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Indicates whether the user can log in as an administrator."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,  # Change to False when email activation is implemented
        help_text=_("Designates whether this user should be treated as active."),
    )

    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ["-date_joined"]
        indexes = [
            models.Index(fields=["email"]),
            models.Index(fields=["username"]),
            models.Index(fields=["is_active", "is_staff"]),
        ]

    def __str__(self):
        return self.username

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_member_since(self) -> str:
        return f"Member since {self.date_joined.strftime('%B %Y')}"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(
        _("avatar"),
        upload_to="avatars/",
        default="avatars/default-avatar.jpg",
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label=_("Username"), widget=forms.TextInput())
    email = forms.EmailField(label=_("E-mail"), widget=forms.EmailInput())
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput())
    password2 = forms.CharField(
        label=_("Confirm Password"), widget=forms.PasswordInput()
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

src/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import get_user_model, login, authenticate
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.views import LogoutView, PasswordResetConfirmView
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.http import JsonResponse, Http404
from .forms import UserRegisterForm
from common.mixins import TitleMixin

from .services.emails import send_confirmation_email

User = get_user_model()


class UserRegisterView(TitleMixin, SuccessMessageMixin, CreateView):
    template_name = "accounts/sign-up.html"
    title = "Sign Up - CryptoChicken"
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("core:index")

    def dispatch(self, request, *args, **kwargs):
        if not request.headers.get("x-requested-with") == "XMLHttpRequest":
            raise Http404()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()

        send_confirmation_email(self.request, self.object)

        username = form.cleaned_data.get("username")
        return JsonResponse(
            {
                "success": True,
                "message": f"Account created for {username}! Please check your email to activate your account.",
            }
        )

    def form_invalid(self, form):
        return JsonResponse({"success": False, "errors": form.errors})


def activate_account_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend="accounts.auth_backend.EmailBackend")
        messages.success(request, "Your account has been successfully activated!")
        return redirect("core:index")
    else:
        messages.error(request, "Activation link is invalid!")
        return redirect("core:index")


class UserLoginView(TitleMixin, TemplateView):
    template_name = "accounts/sign-in.html"
    title = "Sign In - PhotoHub"

    def dispatch(self, request, *args, **kwargs):
        if not request.headers.get("x-requested-with") == "XMLHttpRequest":
            raise Http404()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user_check = User.objects.get(email=email)
            if not user_check.is_active:
                return JsonResponse(
                    {
                        "success": False,
                        "message": "Please confirm your email to activate your account.",
                    }
                )

            user = authenticate(request, username=email, password=password)

            if user is not None:
                login(request, user)
                return JsonResponse(
                    {
                        "success": True,
                        "message": f"Welcome, {user.username}!",
                        "redirect_url": reverse("core:index"),
                    }
                )
            else:
                return JsonResponse(
                    {
                        "success": False,
                        "message": "The password is incorrect. Please try again.",
                    }
                )

        except User.DoesNotExist:
            return JsonResponse(
                {
                    "success": False,
                    "message": f"User with email {email} does not exist.",
                }
            )


class UserLogoutView(LogoutView):

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.success(request, "You are logged out.")
        return super().dispatch(request, *args, **kwargs)

src/templates/accounts/sign-in.html
<div class="pauth box" data-popup="login">
    <button class="pauth__close js-pauth-close"></button>
    <div class="login__popup">
        <div class="section__head text--center">
            <div class="title text--white">Авторизация</div>
        </div>
        <form method="post" action="{% url 'accounts:sign-in' %}" id="signinForm" class="ajax_post_form">
            {% csrf_token %}
            <input type="hidden" name="return_url" value="" />
            <div class="form__input">
                <input
                    type="email"
                    id="email"
                    name="email"
                    required
                    class="input input--nbd"
                    placeholder="E-mail"
                    value="{{ request.POST.email|default:'' }}"
                >
                <div class="input__bg"></div>
            </div>
            <div class="form__input">
                <input
                    type="password"
                    id="password"
                    name="password"
                    required
                    class="input input--nbd"
                    placeholder="Пароль"
                    autocomplete="off"
                    value=""
                >
                <div class="input__bg"></div>
            </div>

            <div class="form__submit">
                <button type="submit" class="btn btn--wall"><span>Войти</span></button>
            </div>
            <div class="form__submit">
                <button class="btn btn--bd btn--bdg btn--wall" type="button" data-open-login="reg"><span>Регистрация</span></button>
            </div>
            <div class="pauth__links">
                <a href="https://crypto-chicken.co/lostpass/" class="pauth__link">Забыли пароль?</a>
            </div>
            <div class="resultgo"></div>
        </form>
    </div>
</div>

src/templates/accounts/sign-up.html
<div class="pauth box" data-popup="reg">
    <button class="pauth__close js-pauth-close"></button>
    <div class="register__popup">
        <div class="section__head text--center">
            <div class="title text--white">Регистрация</div>
        </div>
        <form method="post" action="{% url 'accounts:sign-up' %}" id="signupForm" class="ajax_post_form">
            {% csrf_token %}
            <input type="hidden" name="return_url" value="" />
            <div class="form__input">
                <input
                    type="text"
                    id="username"
                    name="username"
                    class="input input--nbd"
                    required
                    placeholder="Логин*"
                    value="{{ form.username.value|default_if_none:'' }}"
                >
                <div class="input__bg"></div>
            </div>
            <div class="form__input">
                <input
                    type="email"
                    id="email"
                    name="email"
                    required
                    class="input input--nbd"
                    placeholder="E-mail*"
                    value="{{ form.email.value|default_if_none:'' }}"
                >
                <div class="input__bg"></div>
            </div>
            <div class="form__input">
                <input
                    type="password"
                    id="password"
                    name="password1"
                    required
                    class="input input--nbd"
                    placeholder="Пароль*"
                    value="{{ form.password1.value|default_if_none:'' }}"
                    autocomplete="off"
                >
                <div class="input__bg"></div>
            </div>
            <div class="form__input">
                <input
                    type="password"
                    id="confirmPassword"
                    name="password2"
                    class="input input--nbd"
                    placeholder="Пароль еще раз*"
                    autocomplete="off"
                    value="{{ form.password2.value|default_if_none:'' }}"
                >
                <div class="input__bg"></div>
            </div>
            <label class="form__policy">
                <input type="checkbox" name="check_rule" value="1">
                <span class="form__policy-sq"></span>
                <span class="form__policy-t">С <a href="/tos/" target="_blank" rel="noreferrer noopener">правилами сервиса</a> ознакомлен и согласен</span>
            </label>
            <div class="form__submit">
                <button type="submit" name="register" class="btn btn--wall"><span>Регистрация</span></button>
            </div>
            <div class="pauth__enter">
                <div class="pauth__enter-t">У вас есть аккаунт?</div>
                <button class="btn btn--bd btn--bdg" type="button" data-open-login="login"><span>Войти</span></button>
            </div>
            <div class="resultgo"></div>
        </form>
    </div>
</div>